///
/// JAdvancedCommerceInfoIOS.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

#include <fbjni/fbjni.h>
#include "AdvancedCommerceInfoIOS.hpp"

#include "AdvancedCommerceItemDetailsIOS.hpp"
#include "AdvancedCommerceItemIOS.hpp"
#include "AdvancedCommerceRefundIOS.hpp"
#include "JAdvancedCommerceItemDetailsIOS.hpp"
#include "JAdvancedCommerceItemIOS.hpp"
#include "JAdvancedCommerceRefundIOS.hpp"
#include "JVariant_NullType_AdvancedCommerceItemDetailsIOS.hpp"
#include "JVariant_NullType_Array_AdvancedCommerceRefundIOS_.hpp"
#include "JVariant_NullType_Double.hpp"
#include "JVariant_NullType_String.hpp"
#include <NitroModules/JNull.hpp>
#include <NitroModules/Null.hpp>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace margelo::nitro::iap {

  using namespace facebook;

  /**
   * The C++ JNI bridge between the C++ struct "AdvancedCommerceInfoIOS" and the the Kotlin data class "AdvancedCommerceInfoIOS".
   */
  struct JAdvancedCommerceInfoIOS final: public jni::JavaClass<JAdvancedCommerceInfoIOS> {
  public:
    static auto constexpr kJavaDescriptor = "Lcom/margelo/nitro/iap/AdvancedCommerceInfoIOS;";

  public:
    /**
     * Convert this Java/Kotlin-based struct to the C++ struct AdvancedCommerceInfoIOS by copying all values to C++.
     */
    [[maybe_unused]]
    [[nodiscard]]
    AdvancedCommerceInfoIOS toCpp() const {
      static const auto clazz = javaClassStatic();
      static const auto fieldDescription = clazz->getField<JVariant_NullType_String>("description");
      jni::local_ref<JVariant_NullType_String> description = this->getFieldValue(fieldDescription);
      static const auto fieldDisplayName = clazz->getField<JVariant_NullType_String>("displayName");
      jni::local_ref<JVariant_NullType_String> displayName = this->getFieldValue(fieldDisplayName);
      static const auto fieldEstimatedTax = clazz->getField<JVariant_NullType_String>("estimatedTax");
      jni::local_ref<JVariant_NullType_String> estimatedTax = this->getFieldValue(fieldEstimatedTax);
      static const auto fieldItems = clazz->getField<jni::JArrayClass<JAdvancedCommerceItemIOS>>("items");
      jni::local_ref<jni::JArrayClass<JAdvancedCommerceItemIOS>> items = this->getFieldValue(fieldItems);
      static const auto fieldRequestReferenceId = clazz->getField<JVariant_NullType_String>("requestReferenceId");
      jni::local_ref<JVariant_NullType_String> requestReferenceId = this->getFieldValue(fieldRequestReferenceId);
      static const auto fieldTaxCode = clazz->getField<JVariant_NullType_String>("taxCode");
      jni::local_ref<JVariant_NullType_String> taxCode = this->getFieldValue(fieldTaxCode);
      static const auto fieldTaxExclusivePrice = clazz->getField<JVariant_NullType_String>("taxExclusivePrice");
      jni::local_ref<JVariant_NullType_String> taxExclusivePrice = this->getFieldValue(fieldTaxExclusivePrice);
      static const auto fieldTaxRate = clazz->getField<JVariant_NullType_String>("taxRate");
      jni::local_ref<JVariant_NullType_String> taxRate = this->getFieldValue(fieldTaxRate);
      return AdvancedCommerceInfoIOS(
        description != nullptr ? std::make_optional(description->toCpp()) : std::nullopt,
        displayName != nullptr ? std::make_optional(displayName->toCpp()) : std::nullopt,
        estimatedTax != nullptr ? std::make_optional(estimatedTax->toCpp()) : std::nullopt,
        [&]() {
          size_t __size = items->size();
          std::vector<AdvancedCommerceItemIOS> __vector;
          __vector.reserve(__size);
          for (size_t __i = 0; __i < __size; __i++) {
            auto __element = items->getElement(__i);
            __vector.push_back(__element->toCpp());
          }
          return __vector;
        }(),
        requestReferenceId != nullptr ? std::make_optional(requestReferenceId->toCpp()) : std::nullopt,
        taxCode != nullptr ? std::make_optional(taxCode->toCpp()) : std::nullopt,
        taxExclusivePrice != nullptr ? std::make_optional(taxExclusivePrice->toCpp()) : std::nullopt,
        taxRate != nullptr ? std::make_optional(taxRate->toCpp()) : std::nullopt
      );
    }

  public:
    /**
     * Create a Java/Kotlin-based struct by copying all values from the given C++ struct to Java.
     */
    [[maybe_unused]]
    static jni::local_ref<JAdvancedCommerceInfoIOS::javaobject> fromCpp(const AdvancedCommerceInfoIOS& value) {
      using JSignature = JAdvancedCommerceInfoIOS(jni::alias_ref<JVariant_NullType_String>, jni::alias_ref<JVariant_NullType_String>, jni::alias_ref<JVariant_NullType_String>, jni::alias_ref<jni::JArrayClass<JAdvancedCommerceItemIOS>>, jni::alias_ref<JVariant_NullType_String>, jni::alias_ref<JVariant_NullType_String>, jni::alias_ref<JVariant_NullType_String>, jni::alias_ref<JVariant_NullType_String>);
      static const auto clazz = javaClassStatic();
      static const auto create = clazz->getStaticMethod<JSignature>("fromCpp");
      return create(
        clazz,
        value.description.has_value() ? JVariant_NullType_String::fromCpp(value.description.value()) : nullptr,
        value.displayName.has_value() ? JVariant_NullType_String::fromCpp(value.displayName.value()) : nullptr,
        value.estimatedTax.has_value() ? JVariant_NullType_String::fromCpp(value.estimatedTax.value()) : nullptr,
        [&]() {
          size_t __size = value.items.size();
          jni::local_ref<jni::JArrayClass<JAdvancedCommerceItemIOS>> __array = jni::JArrayClass<JAdvancedCommerceItemIOS>::newArray(__size);
          for (size_t __i = 0; __i < __size; __i++) {
            const auto& __element = value.items[__i];
            auto __elementJni = JAdvancedCommerceItemIOS::fromCpp(__element);
            __array->setElement(__i, *__elementJni);
          }
          return __array;
        }(),
        value.requestReferenceId.has_value() ? JVariant_NullType_String::fromCpp(value.requestReferenceId.value()) : nullptr,
        value.taxCode.has_value() ? JVariant_NullType_String::fromCpp(value.taxCode.value()) : nullptr,
        value.taxExclusivePrice.has_value() ? JVariant_NullType_String::fromCpp(value.taxExclusivePrice.value()) : nullptr,
        value.taxRate.has_value() ? JVariant_NullType_String::fromCpp(value.taxRate.value()) : nullptr
      );
    }
  };

} // namespace margelo::nitro::iap
