///
/// AdvancedCommerceItemIOS.kt
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

package com.margelo.nitro.iap

import androidx.annotation.Keep
import com.facebook.proguard.annotations.DoNotStrip
import com.margelo.nitro.core.NullType

/**
 * Represents the JavaScript object/struct "AdvancedCommerceItemIOS".
 */
@DoNotStrip
@Keep
data class AdvancedCommerceItemIOS(
  @DoNotStrip
  @Keep
  val details: Variant_NullType_AdvancedCommerceItemDetailsIOS?,
  @DoNotStrip
  @Keep
  val refunds: Variant_NullType_Array_AdvancedCommerceRefundIOS_?,
  @DoNotStrip
  @Keep
  val revocationDate: Variant_NullType_Double?
) {
  /* primary constructor */

  companion object {
    /**
     * Constructor called from C++
     */
    @DoNotStrip
    @Keep
    @Suppress("unused")
    @JvmStatic
    private fun fromCpp(details: Variant_NullType_AdvancedCommerceItemDetailsIOS?, refunds: Variant_NullType_Array_AdvancedCommerceRefundIOS_?, revocationDate: Variant_NullType_Double?): AdvancedCommerceItemIOS {
      return AdvancedCommerceItemIOS(details, refunds, revocationDate)
    }
  }
}
