///
/// PurchaseUpdatedListenerOptions.kt
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

package com.margelo.nitro.iap

import androidx.annotation.Keep
import com.facebook.proguard.annotations.DoNotStrip
import com.margelo.nitro.core.NullType

/**
 * Represents the JavaScript object/struct "PurchaseUpdatedListenerOptions".
 */
@DoNotStrip
@Keep
data class PurchaseUpdatedListenerOptions(
  @DoNotStrip
  @Keep
  val dedupeTransactionIOS: Variant_NullType_Boolean?
) {
  /* primary constructor */

  companion object {
    /**
     * Constructor called from C++
     */
    @DoNotStrip
    @Keep
    @Suppress("unused")
    @JvmStatic
    private fun fromCpp(dedupeTransactionIOS: Variant_NullType_Boolean?): PurchaseUpdatedListenerOptions {
      return PurchaseUpdatedListenerOptions(dedupeTransactionIOS)
    }
  }
}
