///
/// AdvancedCommerceRefundIOS.kt
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

package com.margelo.nitro.iap

import androidx.annotation.Keep
import com.facebook.proguard.annotations.DoNotStrip
import com.margelo.nitro.core.NullType

/**
 * Represents the JavaScript object/struct "AdvancedCommerceRefundIOS".
 */
@DoNotStrip
@Keep
data class AdvancedCommerceRefundIOS(
  @DoNotStrip
  @Keep
  val jsonRepresentation: Variant_NullType_String?
) {
  /* primary constructor */

  companion object {
    /**
     * Constructor called from C++
     */
    @DoNotStrip
    @Keep
    @Suppress("unused")
    @JvmStatic
    private fun fromCpp(jsonRepresentation: Variant_NullType_String?): AdvancedCommerceRefundIOS {
      return AdvancedCommerceRefundIOS(jsonRepresentation)
    }
  }
}
